name: Fixtures

on:
  push:
    paths:
      - "fixtures/**"
    branches:
      - main

jobs:
  Fixture-Markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update FIXTURES
        run: python3 gen_markdown.py

      - name: Commit Changes
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
