name: Tag Release

on:
  push:
    tags:
      - "[0-9]{4}\\-[0-9]{2}\\-[0-9]{2}"

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add Big Grids
        run: ./add_big_grids

      - name: Tar Test Grids
        run: |
          tar -czf ${{ github.workspace }}/cumulus-geoproc-test-data_${{ github.ref_name }}.tar.gz -C ${{
          github.workspace }}/fixtures .

      - name: Update README
        run: ./gen_markdown

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/cumulus-geoproc-test-data_${{ github.ref_name }}.tar.gz "
          bodyFile: ${{ github.workspace }}/README.md
          makeLatest: true
