name: Tag Release

on:
  push:
    tags:
      - "[0-9]{4}\\-[0-9]{2}\\-[0-9]{2}"

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Geoproc Test Data Archive
        run: |
          curl -L https://github.com/USACE/cumulus-geoproc-test-data/releases/download/${GITHUB_REF_NAME}/cumulus-geoproc-test-data.tar.gz \
          --output cumulus-geoproc-test-data.tar.gz

      - name: Extract Release README
        run: |
          tar -xzvOf ./cumulus-geoproc-test-data.tar.gz */README.md > README.md
          rm -f ./cumulus-geoproc-test-data.tar.gz

      - name: Commit Changes
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
